// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package interview

import (
	"github.com/google/wire"
	"github.com/slack-go/slack"
)

// Injectors from wire.go:

func InitializeStaticQuestionProvider(questions []string) *StaticQuestionProvider {
	staticQuestionProvider := NewStaticQuestionProvider(questions)
	return staticQuestionProvider
}

func InitializeGeminiQuestionProvider(model Model, apiKey APIKey, prompt Prompt) (QuestionProvider, error) {
	questionProvider, err := NewGeminiQuestionProvider(model, apiKey, prompt)
	if err != nil {
		return nil, err
	}
	return questionProvider, nil
}

func InitializeTerminalUI() *TerminalUI {
	terminalUI := NewTerminalUI()
	return terminalUI
}

func InitializeSlackUI(client *slack.Client, channelID ChannelID, userID UserID) *SlackUI {
	slackClientWrapper := NewSlackClientWrapper(client)
	slackUI := NewSlackUI(slackClientWrapper, channelID, userID)
	return slackUI
}

// wire.go:

var slackSet = wire.NewSet(
	NewSlackUI,
	NewSlackClientWrapper, wire.Bind(new(SlackClient), new(*SlackClientWrapper)),
)
