# OpenTelemetry configuration for sending metrics to an OTLP-compatible backend.
telemetry:
  otlp:
    # The endpoint of the OTLP collector (e.g., "localhost:4318" or a Grafana Cloud URL).
    endpoint: ""
    # Set to true if the collector endpoint is not using TLS.
    insecure: false
    # Additional headers to send with OTLP requests, such as for authentication.
    # For Grafana Cloud, this would be a "Authorization" header with a Basic auth credential.
    headers:
      # Authorization: "Basic <your-base64-encoded-credentials>"

# The default topic to use for interviews if not specified on the command line.
topic: "behavioural-interview"
# The API key for provider services like Gemini.
api-key: "<your-gemini-api-key>"
# The user associated with an interview session.
user: "<user-id>"
# The port for the web server to listen on.
port: 8080
# The bot token for the Slack app.
slack-bot-token: "<your-slack-bot-token>"
# The signing secret for the Slack app.
slack-signing-secret: "<your-slack-signing-secret>"

providers:
  gemini:
    model: "gemini-flash-latest"

interviews:
    - id: behavioural-interview
      provider: static
      questions:
        - "Tell me about a time you had to deal with a difficult coworker."
        - "What is your greatest weakness?"
        - "How do you handle stress and pressure?"

    - id: technical-interview
      provider: gemini
      prompt: "You are an interviewer conducting a technical interview for a Senior Software Engineer position."

    - id: product-on-call
      provider: gemini
      prompt: "You are a senior product manager interviewing a candidate for a product manager role. The candidate is being tasked with creating a new product for on-call engineers. Your goal is to assess the candidate's product sense, technical understanding, and communication skills. Ask them about how they would identify the target user, what problems they would solve, and how they would go about designing the product."
