// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/andrewhowdencom/vox/internal/ports/cli"
	"github.com/andrewhowdencom/vox/internal/ports/web"
	"github.com/spf13/cobra"
)

// Injectors from wire.go:

func initializeApp() (*cobra.Command, error) {
	command := cli.NewDebugCmd()
	serveCmd := web.NewServeCmd()
	startCmd := provideStartCmd()
	interviewCmd := newInterviewCmd(startCmd)
	rootCmd := newRootCmd(interviewCmd, serveCmd, command)
	return rootCmd, nil
}
